acquire:
  fetch_game_ids:
    url: "https://raw.githubusercontent.com/beefsack/bgg-ranking-historicals/master/2019-07-08.csv"
  batch_api_call:
    batch_size: 100
    requests_per_minute: 100

upload:
  bucket_name: 'msia423-ktd5131-project-bucket'
  key: 'games.json'

download:
  bucket_name: 'msia423-ktd5131-project-bucket'
  key: 'games.json'

featurize:
  # This is the index at which the one-hot encoded categories start; See One-Hot notebook for details
  index_categories: 12
  # This is the index at which the one-hot encoded mechanics start; See One-Hot notebook for details
  index_mechanics: 95
